apiVersion: v1
kind: Service
metadata:
  name: mcp-sqlite-vec
  namespace: {{ .Values.namespace }}
  labels:
    app: mcp-sqlite-vec
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: mcp-sqlite-vec