apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-sqlite-vec
  namespace: {{ .Values.namespace }}
  labels:
    app: mcp-sqlite-vec
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mcp-sqlite-vec
  template:
    metadata:
      labels:
        app: mcp-sqlite-vec
    spec:
      containers:
        - name: mcp-sqlite-vec
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: OPENAI_API_KEY
            - name: SQLITE_DB_DIR
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMaps.name }}
                  key: SQLITE_DB_DIR
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMaps.name }}
                  key: PORT
          resources:
            {{- toYaml .Values.resources | nindent 12 }}