apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kagent-main-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        namespace: kagent
        environment: dev
  template:
    metadata:
      name: '{{environment}}-kagent'
      namespace: argocd
    spec:
      project: kagent
      source:
        repoURL: https://github.com/papagala/argo-kagent.git
        targetRevision: HEAD
        path: kagent
        helm:
          valueFiles:
            - values.yaml
          parameters:
            - name: global.openai.apiKey
              value: "${OPENAI_API_KEY}"
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true